// react2/calculadora/src/main/Calculator.jsx
/* eslint-disable no-eval */
/* eslint-disable no-unused-vars */
import React, { Component } from "react";
import "./Calculator.css";
import Button from "../components/Button";
import Display from "../components/Display";
import { values } from "lodash";

const initialState = {
  displayValue: "0",
  clearDisplay: false,
  operation: null,
  values: [0, 0],
  current: 0,
};

export default class Calculator extends Component {
  state = { ...initialState };

  constructor(props) {
    super(props);

    this.clearMemory = this.clearMemory.bind(this);
    this.setOperation = this.setOperation.bind(this);
    this.addDgit = this.addDgit.bind(this);
  }

  clearMemory() {
    this.setState({ ...initialState });

    return;
  }

  setOperation(operation) {
    if (this.state.current === 0) {
      this.setState({ operation, current: 1, clearDisplay: true });
    } else {
      const equals = operation === "=";
      const currentOperation = this.state.operation;
      const values = [...this.state.values];

      try {
        values[0] = eval(`${values[0]} ${currentOperation} ${values[1]}`);
      } catch (e) {
        console.log(e, values);
        values[0] = this.state.values[0]
      }

      this.setState({
        displayValue: values[0],
        operation: equals ? null : operation,
        current: equals ? 0 : 1,
        clearDisplay: !equals,
        values,
      });
    }
  }

  addDgit(n) {
    if (n === "." && this.state.displayValue.includes(".")) {
      return;
    }

    const clearDisplay =
      this.state.displayValue === "0" || this.state.clearDisplay;
    const currentValue = clearDisplay ? "" : this.state.displayValue;
    const displayValue = currentValue + n;
    this.setState({ displayValue, clearDisplay: false });

    if (n !== ".") {
      const i = this.state.current;
      const newValue = parseFloat(displayValue);
      const values = [...this.state.values];
      values[i] = newValue;
      this.setState({ values });

      console.log(values);
    }
  }

  render() {
    return (
      <div className="calculator">
        <Display value={this.state.displayValue} />
        <Button label="AC" click={this.clearMemory} triple />
        <Button label="/" click={this.setOperation} operation />
        <Button label="7" click={this.addDgit} />
        <Button label="8" click={this.addDgit} />
        <Button label="9" click={this.addDgit} />
        <Button label="*" click={this.setOperation} operation />
        <Button label="4" click={this.addDgit} />
        <Button label="5" click={this.addDgit} />
        <Button label="6" click={this.addDgit} />
        <Button label="-" click={this.setOperation} operation />
        <Button label="1" click={this.addDgit} />
        <Button label="2" click={this.addDgit} />
        <Button label="3" click={this.addDgit} />
        <Button label="+" click={this.setOperation} operation />
        <Button label="0" click={this.addDgit} double />
        <Button label="." click={this.addDgit} />
        <Button label="=" click={this.setOperation} operation />
      </div>
    );
  }
}

// vue/calculator/src/main/Calculator.vue
<template>
    <div class="calculator">
        <Display :value="displayValue"/>
        <Button label="AC" triple @onClick="clearMemory"/>      
        <Button label="/" operation @onClick="setOperation"/>      
        <Button label="7" @onClick="addDigit"/>      
        <Button label="8" @onClick="addDigit"/>      
        <Button label="9" @onClick="addDigit"/>      
        <Button label="*" operation @onClick="addDigit"/>      
        <Button label="4" @onClick="addDigit"/>      
        <Button label="5" @onClick="addDigit"/>      
        <Button label="6" @onClick="addDigit"/>      
        <Button label="-" operation @onClick="setOperation"/>      
        <Button label="1" @onClick="addDigit"/>      
        <Button label="2" @onClick="addDigit"/>      
        <Button label="3" @onClick="addDigit"/>      
        <Button label="+" operation @onClick="setOperation"/>      
        <Button label="0" double @onClick="addDigit"/>      
        <Button label="." @onClick="addDigit"/>      
        <Button label="=" operation @onClick="setOperation"/>      
          
    </div>
</template>

<script>
import Button from '../components/Button.vue'
import Display from '../components/Display.vue'


export default {
    data: function() {
        return {
            displayValue: "0",
            clearDisplay: false,
            operation: null,
            values: [0, 0],
            current: 0
        }
    },

    components: { Button, Display },
    methods: {
        clearMemory() {
            Object.assign(this.$data, this.$options.data())
        },

        setOperation(operation) {
            if (this.current === 0) {
                this.operation = operation
                this.current = 1
                this.clearDisplay = true
            } else {
                const equals = operation === '='
                const currentOperation = this.operation

                try {
                    this.values[0] = eval(
                        `${this.values[0]} ${currentOperation} ${this.values[1]}`
                    )
                } catch(err) { this.$emit('onError', err) }

                this.values[1] = 0
                this.displayValue = this.values[0]
                this.operations = equals ? null : operation
                this.current = equals ? 0 : 1
                this.clearDisplay = !equals
            }
        },

        addDigit(n) {
            if (n === '.' && this.displayValue.includes(".")) return
        
            const clearDisplay = this.displayValue === "0" || this.clearDisplay === true
            const currentValue = clearDisplay ? "" : this.displayValue
            const displayValue = currentValue + n

            this.displayValue = displayValue
            this.clearDisplay = false
            this.values[this.current] = displayValue

            // if (n !== '.') {
            //     const i = this.current
            //     const newValue = parseFloat(displayValue)
            //     this.values[i] = newValue
            // }
        }

    }
}
</script>

<style>
    .calculator {
        height: 320px;
        width: 235px;
        border-radius: 5px;
        overflow: hidden;

        display: grid;
        grid-template-columns: repeat(4, 25%);
        grid-template-rows: 1fr, 48px, 48px, 48px, 48px, 48px;
    }
</style>
